name: Publish NPM Package to Github

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Version of Node to use'
        required: true
        type: string
        default: '20.x'
    outputs:
      test-results:
        description: "Results from npm run test"
        value: ${{ jobs.run-tests.outputs.test-results }}

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      test-results: ${{ steps.test-results.outputs.test-results }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Configure Github NPM Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install Dependencies
        run: npm ci
      
      - name: Run Tests
        id: test-results
        run: |
          echo 'test-results<<EOF' >> $GITHUB_OUTPUT
          npm run test 2>&1 | tee >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT