name: Publish NPM Package to Github

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Version of Node to use'
        required: true
        type: string
        default: '20.x'

jobs:
  build-and-plublish:
    name: Build and Publish NPM Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Configure Github NPM Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}