name: Release Please

on:
  workflow_call:
    inputs:
      release-type:
        description: 'The type of release to perform'
        required: true
        type: string
        default: 'simple'
    secrets:
      BOT_ID:
        required: true
      BOT_KEY:
        required: true
    outputs:
      release-created:
        description: 'Whether a release was created'
        value: ${{ jobs.release-please.outputs.releases_created }}

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: ${{ inputs.release-type }}
