name: Release Management

on:
  workflow_call:
    inputs:
      release-type:
        description: 'The type of release to perform'
        required: true
        type: string
        default: 'simple'
    outputs:
      release-created:
        description: 'Whether a release was created'
        value: ${{ steps.release-please.outputs.release-created }}

jobs:
  release-please:
    name: Rlease Please
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: ${{ var.release-type }}
